### PR TITLE
use default options when none provided

### LINKED ISSUE #28: Message not propagating in 1.7.1
Changes between versions 1.5.1 and 1.7.1 appear to have broken the message field propagation when using createError:

const myError = createError('BadError', { message: "This is bad"});
var theError = new myError();
console.log(theError.message) 

output of message field is undefined.... 

Works great in 1.5.1, broken in 1.7.1

### PR DESCRIPTION
**Pull request by ecwyne**
fixes #28

### CODE REVIEW

**Comment by ecwyne** [comment]
@thebigredgeek I wasn't sure if you wanted the `dist` changes committed or not. Let me know if there are any changes you'd like me to make!

Thanks for an amazing package!

**Comment by lxcid** [comment]
What is the reason to have 2 error config though?

**Comment by ecwyne** [comment]
```javascript
const FooError = createError(baseConfig);

throw new FooError(config);
```

`baseConfig` provides all of the defaults while `config` *may* override or add additional values.

**Comment by lxcid** [comment]
Thanks @ecwyne, I figure out on the side though. I came up with a different PR which is mostly identical with yours except with the order the config get merged though, but a lot of it references on the existing PRs.

Thanks for the quick explanation!

**Comment by thebigredgeek** [comment]
I believe this functionality is now already implemented.  I am about to release `1.7` so once you get a chance to upgrade please let me know if this PR is still necessary

**Pull request closed without merging**
