### PR TITLE
Revert "Revert "Make serialized error spec compliant""

### PR DESCRIPTION
**Pull request by theGlenn**

### CODE REVIEW

**Comment by lxcid** [comment]
Hey sorry, what input do you need me for this? it looks like it ready to be merge?

**Comment by lxcid** [comment]
The code seems alright, I just make the change so that the CI pass. See #52 

I hope I don't go MIA again, let me know if you guys see any issue.

**Comment by thebigredgeek** [comment]
Can you get the tests to pass?

**Comment by lxcid** [comment]
I fix the failing test in #52 (It a PR for merging to this PR)… I think once its reviewed and merged this should pass. 👍

**Pull request merged**
