### PR TITLE
Return the serialized form of the real error when a remote error occurs

### PR DESCRIPTION
**Pull request by cschroeter**
If you merge multiple schemas, the GraphQL error object looks slightly different.

```typescript
import { mergeSchemas } from 'graphql-tools';

mergeSchemas({ schemas: [localSchema, remoteSchema] });
```
This PR address this issue.

### CODE REVIEW

**Comment by thebigredgeek** [comment]
Can we do this without adding Lodash as a dep?

**Comment by cschroeter** [comment]
Mhh I just added the get function `"lodash.get": "^4.4.2"`. If you don't want this dependency we have to write code like `errors && errors[0] && errors[0].originalError`.

In my opinion the better readability outweighs the disadvantages. But this is your call

**Comment by cschroeter** [comment]
But I found another bug. If you have a query like this 
```graphql
{
  SystemInformation {
    UpdatePolicy {
      isAutoUpdateEnabled
    }
    OperatingSystem {
      name
      version
    }
  }
}
```

and you throw in the UpdatePolicy resolver an apollo-error the response is not formatted like expected.

```json
{
  "data": {
    "SystemInformation": {
      "UpdatePolicy": null,
      "OperatingSystem": {
        "name": "Edobian",
        "version": "17.5.0"
      }
    }
  },
  "errors": [
    {
      "message": "You do not have the necessary permissions",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "SystemInformation",
        "UpdatePolicy"
      ]
    }
  ]
}
```

**Comment by thebigredgeek** [comment]
Yep it looks like it's not properly serializing.  But yeah, I'd prefer not to include any more deps if possible

**Comment by thebigredgeek** [comment]
Any updates here?

**Comment by thebigredgeek** [comment]
Closing this as there hasn't been any activity.  Feel free to re-open it when you have time

**Pull request closed without merging**
